name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]  # Trigger deployment on push to the main branch
  workflow_dispatch:  # Allow manual trigger from GitHub Actions UI

permissions:
  contents: read  # Read repository contents
  pages: write    # Write to GitHub Pages
  id-token: write # To authenticate for GitHub Pages deployment

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the repository code
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Set the Ruby version compatible with your Jekyll site
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --destination ./_site
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site  # Path to the Jekyll build output

  deploy:
    needs: build  # This job depends on the build job being successful
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Use the deploy-pages action for GitHub Pages deployment
